export const productCategories = {
  INSECTICIDES: "INSECTICIDES",
  RODENTICIDES: "RODENTICIDES",
  BAITS_AND_BAIT_STATIONS: "BAITS_AND_BAIT_STATIONS",
  TRAPS_AND_MONITORING: "TRAPS_AND_MONITORING",
  DUSTS_AND_POWDERS: "DUSTS_AND_POWDERS",
  FUMIGANTS: "FUMIGANTS",
  GROWTH_REGULATORS: "GROWTH_REGULATORS",
  REPELLENTS: "REPELLENTS",
  BIOLOGICAL_CONTROLS: "BIOLOGICAL_CONTROLS",
  EXCLUSION_MATERIALS: "EXCLUSION_MATERIALS",
  FOAMING_AGENTS: "FOAMING_AGENTS",
  DISINFECTANTS: "DISINFECTANTS",
  BIRD_CONTROL: "BIRD_CONTROL",
  TERMITICIDES: "TERMITICIDES",
  AEROSOLS_AND_FOGGERS: "AEROSOLS_AND_FOGGERS",
} as const;

export type ProductCategory =
  (typeof productCategories)[keyof typeof productCategories];
